name: Hacktoberfest PR Label

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  issues: write    # top-level permissions are applied to the whole workflow

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Add Hacktoberfest label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const now = new Date();
            const month = now.getMonth() + 1;
            if (month === 10) {
              // For pull_request_target, context.issue.number refers to the PR number in the base repo
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['hacktoberfest']
              });
              console.log('Added hacktoberfest label to PR');
            }