name: Hacktoberfest PR Label

on:
  pull_request:
    types: [opened, reopened]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
    - name: Add Hacktoberfest label
      uses: actions/github-script@v7
      with:
        script: |
          const now = new Date();
          const month = now.getMonth() + 1; // JavaScript months are 0-based
          
          // Only auto-label during October
          if (month === 10) {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['hacktoberfest']
            });
            
            console.log('Added hacktoberfest label to PR');
          }
